version: 2.1

orbs:
  python: circleci/python@1.1.0
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: |
            pytest --version
          name: Check pytest version
      - run:
          command: export DJANGO_SETTINGS_MODULE=message_in_a_bottle.settings
          name: Set path for pytest
      - run:
          command: pytest
          name: Run test suite
