version: 2.1

orbs:
  python: circleci/python@1.1.0
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/python:3.9.7
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: defaultuser
          POSTGRES_DB: postgres
    environment:
      PGHOST: 127.0.0.1
      PGUSER: defaultuser
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            python3 -m virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            export DJANGO_SETTINGS_MODULE=message_in_a_bottle.settings
            pytest
          name: Activate virtual env, install requirements, and run test suite
