# Generated by Django 3.2.8 on 2021-10-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('message', models.TextField()),
                ('name', models.CharField(default='Anonymous', max_length=50))
            ],
        ),
    ]
