# Generated by Django 3.2.8 on 2021-10-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='My Story', max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
